Initial GridAdmin endpoints
gridsuite/user-admin-server pull request #25
Opened 2024-01-15 09:14 UTC by Tristan-WorkGH

For [gridsuite/gridadmin-app](//github.com/gridsuite/gridadmin-app):
* add new endpoints
* set correct methods and return code for REST endpoints _(not `userExists` which is used by the gateway service)_
* return DTO instead of database entities
* fix services calls not transactional
* use sub instead of uuid

2024-01-16 20:25 UTC, etiennehomer requested changes

2024-02-09 19:30 UTC, antoinebhs reviewed
Some comments, remove the TODO and comments left as we’re not completely sure we will want to do it later….
Not sure why we need a search ?

2024-02-16 15:55 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @PutMapping(value = "/users/{sub}")
to match RESTful standards

2024-02-16 15:59 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/useradmin/server/repository/UserAdminRepository.java
> +    boolean existsBySub/*IgnoreCase*/(@NonNull String sub);
that was a question I haven't a response: is the API case sensitive or insensitive for usernames/ID/sub?

2024-02-21 13:25 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/repository/UserAdminRepository.java
> +    boolean existsBySub/*IgnoreCase*/(@NonNull String sub);
We keep it case sensitive for the moment

2024-02-21 14:02 UTC, etiennehomer requested changes

2024-02-21 14:07 UTC, etiennehomer requested changes

2024-02-21 14:07 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @PutMapping(value = "/users/{sub}")
In GridSuite, we use POST methods for element creation. To be reverted

2024-02-21 14:20 UTC, etiennehomer requested changes

2024-02-21 14:20 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/service/DtoConverter.java
> +    private DtoConverter() {
We usually implement the toEntity() in the dto class and the toDto() in the entity class.

2024-02-21 14:43 UTC, etiennehomer requested changes

2024-02-21 14:43 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +        //TODO notFound instead of noContent
Comment to remove

2024-02-21 14:43 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @RequestMapping(value = "/users/{sub}/isElevatedUser", method = RequestMethod.HEAD)
RequestMapping(value = "/users/{sub}/isAdmin

2024-02-21 14:43 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +        return service.userIsAuthorizedAdmin(userId)
return service.**userIsAdmin**(userId)

2024-02-21 14:53 UTC, etiennehomer requested changes

2024-02-21 14:53 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @SecurityRequirement(name = "userType", scopes = {"admin"})
It's not working ? And we didn't decide we want to use this annotation

2024-02-21 16:07 UTC, etiennehomer requested changes

2024-02-21 16:07 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/service/AbstractCommonService.java
> +    protected boolean isAdmin(@NonNull String sub) {
isAdmin() and assertIsAdmin shoud stay in UserAdminService.
And remove **admins.isEmpty() ||** !

2024-02-22 15:35 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/useradmin/server/service/DtoConverter.java
> +    private DtoConverter() {
that was to have clear separation between rest and repository layers

2024-02-22 15:36 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +        //TODO notFound instead of noContent
that's a todo to do later (another pr)

2024-02-22 15:38 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @RequestMapping(value = "/users/{sub}/isElevatedUser", method = RequestMethod.HEAD)
That is to not confuse technical terms with future feature of role "admin" in business terms.

2024-02-22 16:29 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @RequestMapping(value = "/users/{sub}/isElevatedUser", method = RequestMethod.HEAD)
We can use isAdmin now as only technical admins will be autorized by now. We can change it later after some evolution

2024-02-22 16:36 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +        //TODO notFound instead of noContent
The TODO is to removed. When we check the existence of a resource, we return a 204 for non existing resources

2024-02-22 16:46 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @SecurityRequirement(name = "userType", scopes = {"admin"})
oh yes, have forget to fix this part  
the goal is to specify in the swagger that some endpoints are restricted to admin users

2024-02-22 16:57 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/useradmin/server/service/DtoConverter.java
> +    public static UserInfos toDto(@Nullable final UserInfosEntity entity, Predicate<String> isAdminFn) {
no, because it is not the is-admin of the current user, but is the is-admin of the user retrieve in the entity

2024-02-23 09:23 UTC, etiennehomer requested changes

2024-02-23 09:23 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/ApiRestriction.java
> +package org.gridsuite.useradmin.server;
It's too complicated for small benefit. To be removed

2024-02-23 09:23 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/SwaggerConfig.java
> +    @Bean
same

2024-02-26 09:06 UTC, etiennehomer approved these changes

2024-02-26 11:48 UTC, antoinebhs approved these changes

2024-03-07 15:35 UTC, antoinebhs commented
For later ?
When a user already exists, the following error is thrown:
```
Error while deleting user

Error while adding user "admin1":
HttpResponseError : 500 Internal Server Error, message : could not execute statement [ERROR: duplicate key value violates unique constraint "user_infos_sub_key"
  Detail: Key (sub)=(admin1) already exists.] [insert into user_infos (sub,id) values (?,?)]; SQL [insert into user_infos (sub,id) values (?,?)]; constraint [user_infos_sub_key]
```
We should add a check

2024-03-08 10:51 UTC, etiennehomer requested changes
Last commit to revert !

2024-03-08 10:51 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +        //TODO authorize if userId == sub (if user ask own data)
Yes to remove

2024-03-08 15:58 UTC, etiennehomer approved these changes

2024-03-08 16:17 UTC, merged