add user profile
gridsuite/user-admin-server pull request #29
Opened 2024-03-21 08:22 UTC by dbraquart

2024-04-02 13:02 UTC, etiennehomer requested changes

2024-04-02 13:02 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +    public void updateProfile(UUID profileUuid, String userId, UserProfile userProfile) {
You already have the "profileUuid" in the userProfile

2024-04-02 13:02 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @PutMapping(value = "/profiles/{profileUuid}")
You can remove profileUuid and work with userProfile nope ?

2024-04-02 13:02 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +        service.updateUser(sub, userId, userInfos);
You can remove "sub" and work with userInfos nope ?

2024-04-02 13:56 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/dto/UserProfile.java
> +    Boolean validity
valid ?

2024-04-02 15:33 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +    public long delete(List<String> subs, String userId) {
I saw a warning, cant remener which. I will revert to validate.

2024-04-02 16:10 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/entity/UserInfosEntity.java
> +    public void update(UserInfos userInfos, Optional<UserProfileEntity> userProfileEntity) {
yes done

2024-04-02 16:10 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +    public long delete(List<String> subs, String userId) {
well I cant see it .. I will revert

2024-04-02 16:16 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +    public void updateUser(String sub, String userId, UserInfos userInfos) {
If I remove, I will have a warning in Controller (unused param). what to do ?

2024-04-02 16:43 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/entity/UserProfileEntity.java
> +        Boolean globalValidity = null;
yes done

2024-04-02 16:43 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/dto/UserProfile.java
> +    Boolean validity
renamed as allParametersLinksValid

2024-04-02 16:53 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +    public void updateProfile(UUID profileUuid, String userId, UserProfile userProfile) {
If I remove it, I will have a warning in Controller (unused param). what to do ?

2024-04-02 16:56 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +        service.updateUser(sub, userId, userInfos);
no I need both

2024-04-02 18:32 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +        service.updateUser(sub, userId, userInfos);
Yes as discussed, it's the classic way to update a resource with rest api

2024-04-03 14:53 UTC, etiennehomer commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +    public void updateProfile(UUID profileUuid, String userId, UserProfile userProfile) {
It's fine like this as we keep the profileUuid in the endpoint

2024-04-04 11:46 UTC, TheMaskedTurtle requested changes

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @PostMapping(value = "/profiles/{profileName}")
This should be a post on /profiles with UserProfile as body

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
Can you make a dedicated UserProfileController ?

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @ApiResponse(responseCode = "200", description = "The user exist")
This endpoint feels a bit clumsy, why not GET /users/{sub} that returns a UserInfos, that holds a UserProfile itself ? Otherwise, complete the GET /profiles endpoints to filter on sub ?

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +                                               @RequestBody UserInfos userInfos) {
alignment

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +                                               @RequestBody UserProfile userProfile) {
Alignment

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @ApiResponse(responseCode = "404", description = "One or more profile(s) not found")
Maybe this should not happen, no ? If we want to delete all profiles, we don't really mind if there were no profiles, what do you think ?

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/repository/UserAdminRepository.java
Maybe rename UserInfosRepository to remain consistent ?

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/entity/UserProfileEntity.java
> +    }
This creates a dependency Entity -> Dto, according to me it's not a good practice

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/entity/UserInfosEntity.java
>      }
Same

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/DirectoryService.java
> +                }).getBody();
restTemplate.getForObject ?

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +    public void updateUser(String sub, String userId, UserInfos userInfos) {
Should really a user sub be updatable ?

2024-04-04 11:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +                .toList();
It would be much cleaner to produce an event in directory-server on deletion and subscribe to those events here

2024-04-08 07:21 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/RestResponseEntityExceptionHandler.java
> +                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(userAdminException.getType());
probably not used by the Front.

2024-04-08 07:25 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @PostMapping(value = "/profiles/{profileName}")
yes! I copy/paste createUser without thinking.

2024-04-08 12:25 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @ApiResponse(responseCode = "200", description = "The user exist")
ok, I will use GET /profiles?sub={sub}

2024-04-08 12:33 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +                .toList();
Why not changing the user name? To fix a typo for instance.

About the "dead links" detection, I choose a simple/quick way to do it. But this is a bigger design question cause we have many "links" between objects (filters, aleas, params), and we should address this question separatly I think, not in this PR.

2024-04-08 14:07 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/RestTemplateConfig.java
maybe there is something to improve here. but we use it in all (?) our servers, so maybe we should address this in a separate PR.

2024-04-08 14:59 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/entity/UserProfileEntity.java
> +    }
I changed it.
For the record, we do that everywhere in modification-server.

2024-04-09 15:36 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
In fact, I saw a TS to start doing this (having N controllers).
So I did it.

2024-04-11 08:45 UTC, TheMaskedTurtle requested changes

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/controller/UserProfileController.java
> +    }
Shouldn't we restrict access to this endpoint too ?

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/controller/UserProfileController.java
> +    }
The MediaType is not the same between the "produces=" and the contenttype()

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/entity/UserProfileEntity.java
> +    }
Why not `public UserProfile toDto()` ?

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/DirectoryService.java
Should we rather check on directory server elements or directly in loadflow server ? What if it is desynchronized between those ? Which one should be the source of truth ?

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +            profiles = user.getProfile() == null ? List.of() : userProfileRepository.findById(user.getProfile().getId()).stream().toList();
We can do that in one query ?

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +        Set<UUID> missingParametersUuids = allParametersUuidInAllProfiles
You can do a Set difference instead, it would be much more efficient

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +                .map(UserProfileEntity::getLoadFlowParameterId)
So when we will have several parameters for all the computation services, we will have to do that once for each of them...

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +    }
Is that following my remark on DTO/Entity dependency ? If you want to really remove this dependency you should move the static methods from UserProfileEntity to here. But as it is now it feels a bit mixed and the dependency still exists.

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/UserAdminTest.java
> +    void testUpdateUser() throws Exception {
Can you split that in several tests ?

2024-04-11 08:45 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/UserProfileTest.java
> +public class UserProfileTest {
Can you split the tests to make them more readable ? And maybe extract the API call method to util method, still to make it more readable

2024-04-11 08:46 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/RestTemplateConfig.java
Yes ok, not blocking though, maybe I'll create a ticket

2024-04-11 08:47 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @ApiResponse(responseCode = "404", description = "One or more profile(s) not found")
Yes ok, let's just keep it like that !

2024-04-12 16:03 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/controller/UserProfileController.java
> +    }
I need an unrestricted end-point callable from the study-server (cf https://github.com/gridsuite/study-server/pull/541/files#diff-7f2fd0eae994acb21bdc048965305dc72dc34fd78a899f6d2e7dce95b591074e), to retrieve the profile of/from any user

2024-04-12 16:49 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +                .map(UserProfileEntity::getLoadFlowParameterId)
we can use mapMulti to retrieve all parameters in the same stream

2024-04-12 16:49 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +        Set<UUID> missingParametersUuids = allParametersUuidInAllProfiles
how can I do that ?

2024-04-12 16:49 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +    }
yes done

2024-04-12 17:06 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/entity/UserProfileEntity.java
> +    }
this code has moved to UserProfileService now

2024-04-15 08:28 UTC, dbraquart commented on src/test/java/org/gridsuite/useradmin/server/UserProfileTest.java
> +public class UserProfileTest {
yes done

2024-04-15 09:42 UTC, dbraquart commented on src/test/java/org/gridsuite/useradmin/server/UserAdminTest.java
> +    void testUpdateUser() throws Exception {
yes done

2024-04-15 10:10 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +            profiles = user.getProfile() == null ? List.of() : userProfileRepository.findById(user.getProfile().getId()).stream().toList();
user->profile is a one-way relation, then I cannot do this in single query.
This is not a performance concern because these are 2 very fast queries.

2024-04-15 15:24 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +        Set<UUID> missingParametersUuids = allParametersUuidInAllProfiles
`Set<UUID> missingParametersUuids = Sets.difference(allParametersUuidInAllProfiles, existingParametersUuids);` Actually I checked the implementation and I'm not sure it would be much more efficient ^^ So as you wish, maybe it's a bit more readable ?

2024-04-16 14:38 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +        user.setProfile(profile.orElse(null));
Shouldn't we return a bad_input if the profile is not define ?

2024-04-16 14:38 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/DirectoryService.java
> +        String path = UriComponentsBuilder.fromPath(ELEMENTS_SERVER_ROOT_PATH).toUriString() + "?strictMode=false&ids=" + ids;
You can use queryParam to add the query params

2024-04-16 14:38 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/entity/UserInfosEntity.java
> +    private UserProfileEntity profile;
This makes impossible to delete a profile if it is set on any user. Is this what we want ? Maybe we should have a proper error when we do this, because for now we just get the foreign key constraint violation in the snack bar

2024-04-16 14:38 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/DirectoryService.java
> +        List<ElementAttributes> existingElementList = restTemplate.exchange(directoryServerBaseUri + path, HttpMethod.GET, null,
No error handling on external HTTP request ?

2024-04-16 16:26 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +        Set<UUID> missingParametersUuids = allParametersUuidInAllProfiles
yes done

2024-04-16 16:27 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +        user.setProfile(profile.orElse(null));
we have a common habit to return 404 if we try to update a missing resource.

2024-04-16 16:30 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/DirectoryService.java
> +        List<ElementAttributes> existingElementList = restTemplate.exchange(directoryServerBaseUri + path, HttpMethod.GET, null,
In case of error here, this will end into an error 500 for the caller (admin-app here). No need to have more.

2024-04-16 16:33 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/entity/UserInfosEntity.java
> +    private UserProfileEntity profile;
yeah.. i know. This is a cheap way to have an error/consistency managment of the relation between user/profile. I wish we could have a PO to state if this is acceptable or not.

2024-04-16 16:54 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/service/DirectoryService.java
> +        String path = UriComponentsBuilder.fromPath(ELEMENTS_SERVER_ROOT_PATH).toUriString() + "?strictMode=false&ids=" + ids;
yes done

2024-04-17 10:07 UTC, dbraquart commented on src/main/java/org/gridsuite/useradmin/server/entity/UserInfosEntity.java
> +    private UserProfileEntity profile;
I still rely on the violation constraint, but I return a 422 status in this case, and the Front will display a specific message

2024-04-17 14:41 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +        user.setProfile(profile.orElse(null));
No I agree if the user is missing, but if the profile is missing ? Here if the profile does not exist we just set it to null but we don't throw.

2024-04-17 14:52 UTC, TheMaskedTurtle approved these changes

2024-04-18 08:22 UTC, etiennehomer approved these changes

2024-04-18 09:17 UTC, merged