Add and manage announcements
gridsuite/user-admin-server pull request #30
Opened 2024-03-29 14:27 UTC by flomillot

2024-04-02 14:07 UTC, TheMaskedTurtle requested changes

2024-04-02 14:07 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/UserAdminTest.java
>      }
Can you separete the tests for OK results and for forbidden ?

2024-04-02 14:07 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/UserAdminTest.java
> +    }
Same

2024-04-02 14:07 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/AnnouncementService.java
> +        }
Maybe this can be handled in the EmitMessage method

2024-04-03 12:57 UTC, flomillot commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    public ResponseEntity<List<AnnouncementEntity>> sendCancelMaintenanceMessage(@RequestHeader("userId") String userId) {
Ah yes forgot, thanks

2024-04-03 13:00 UTC, flomillot commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @Operation(summary = "Get all the messages")
Yes sometimes I kept the previous word "messages" or "maintenance messages"... didn't want to change everything but here it's legit

2024-04-03 13:02 UTC, flomillot commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @Operation(summary = "Send a message to all the connected users")
It's the opposite IMO, storing it is purely technical and the notifying is the real functionnality.

2024-04-03 13:04 UTC, flomillot commented on src/main/java/org/gridsuite/useradmin/server/UserAdminController.java
> +    @Operation(summary = "Cancel and delete a message")
Same as above. But to be coherent, I could remove the "delete" part.

2024-04-03 13:04 UTC, flomillot commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
I know, cf above

2024-04-03 13:07 UTC, flomillot commented on src/test/java/org/gridsuite/useradmin/server/UserAdminTest.java
>      }
I just updated and completed the test, I prefer to keep them like it was (TL already told me few times to change only the necessary so that's what I do now)

2024-04-03 13:10 UTC, flomillot commented on src/main/java/org/gridsuite/useradmin/server/service/AnnouncementService.java
> +        }
I would have done that also, but it's not a big deal and does not change that much so I kept the existing code

2026-06-23 10:30 UTC, closed without merging