Set default max builds and cases for users
gridsuite/user-admin-server pull request #40
Opened 2024-08-27 12:17 UTC by achour94

2024-08-28 15:59 UTC, TheMaskedTurtle requested changes
You should test that:
- with values in the configuration 1. when you create a profile with no values, default ones are stored 2. when you query values for a user with no profile, default ones are returned
- with no values in the configuration 1. when you create a profile with no values, nulls are stored 2. when you query values for a user with no profile, nulls are returned

2024-08-28 15:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminApplicationProps.java
> +    private Optional<Integer> defaultAllowedCases = Optional.empty();
nit: defaultMaxAllowedCases ?

2024-08-28 15:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminApplicationProps.java
> +    private Optional<Integer> defaultAllowedBuilds = Optional.empty();
nit: defaultMaxAllowedBuilds ?

2024-08-28 15:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/controller/UserAdminController.java
> +    public ResponseEntity<Integer> getUserProfileMaxBuilds(@PathVariable("sub") String sub) {
nit: getUserProfileMaxAllowedBuilds ?

2024-08-28 15:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +        this.applicationProps = Objects.requireNonNull(applicationProps);
I don't think the requireNonNull is very useful they're all injected beans anyway... But as it is done like that everywhere else, ok.

2024-08-28 15:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +        return userProfile == null ? applicationProps.getDefaultAllowedCases().orElse(null) : userProfile.maxAllowedCases();
```suggestion
        return self.getUserProfile(sub)
            .map(UserProfile::maxAllowedCases)
            .orElse(applicationProps.getDefaultAllowedCases().orElse(null));
```

2024-08-28 15:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserAdminService.java
> +        return userProfile == null ? applicationProps.getDefaultAllowedBuilds().orElse(null) : userProfile.maxAllowedBuilds();
```suggestion
        return self.getUserProfile(sub)
            .map(UserProfile::maxAllowedBuilds)
            .orElse(applicationProps.getDefaultAllowedBuilds().orElse(null));
```

2024-08-28 15:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminApplicationProps.java
> +    private Optional<Integer> defaultAllowedCases = Optional.empty();
Not sure you need to define as Optional<Integer>, just integer must be enough, it's always used in the code with orElse(null) anyway. With Integer it will default to null directly.

2024-08-28 15:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/UserAdminApplicationProps.java
> +    private Optional<Integer> defaultAllowedBuilds = Optional.empty();
Same remark as above

2024-08-28 15:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/useradmin/server/service/UserProfileService.java
> +        }
You can set that in toEntity directly no ? 
```
private UserProfileEntity toEntity(final UserProfile userProfile) {
        Objects.requireNonNull(userProfile);
        return new UserProfileEntity(
            UUID.randomUUID(),
            userProfile.name(),
            userProfile.loadFlowParameterId(),
            Optional.ofNullable(userProfile.maxAllowedCases()).orElse(applicationProps.getDefaultAllowedCases().orElse(null)),
            Optional.ofNullable(userProfile.maxAllowedBuilds()).orElse(applicationProps.getDefaultAllowedBuilds().orElse(null))
        );
}
```

2024-08-29 12:23 UTC, achour94 commented on src/main/java/org/gridsuite/useradmin/server/UserAdminApplicationProps.java
> +    private Optional<Integer> defaultAllowedCases = Optional.empty();
It's just twt different ways to do it and i like handle to handle nullables with Optional :)

2024-08-30 08:51 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/NoQuotaTest.java
> +                .andReturn();
Here you don't associate the user with the profile, so you test the same case as below. To do so, you have to call PUT /users/{sub} after you created the user. And you can separate in 3 tests actually, 1 for the profile only, 1 for the user with the profile and 1 for the user without profile.

2024-08-30 08:51 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/NoQuotaTest.java
> +        assertTrue(content.isEmpty() || content.equals("null"));
It should be just empty or just null, can you keep just one ?

2024-08-30 08:51 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/NoQuotaTest.java
> +    public void testProfileCreationAndQuotas() {
you don't need public with junit5

2024-08-30 08:51 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/UserProfileTest.java
> +        MvcResult result = mockMvc.perform(get("/" + UserAdminApi.API_VERSION + "/users/{sub}/profile/max-builds", ADMIN_USER)
```
private Integer getMaxAllowedCases(String user) throws Exception {
        MvcResult result = mockMvc.perform(get("/" + UserAdminApi.API_VERSION + "/users/{sub}/profile/max-cases", user)
                .header("userId", user)
            )
            .andExpect(status().isOk())
            .andReturn();
        return objectMapper.readValue(result.getResponse().getContentAsString(), Integer.class);
    }

    private Integer getMaxAllowedBuilds(String user) throws Exception {
        MvcResult result = mockMvc.perform(get("/" + UserAdminApi.API_VERSION + "/users/{sub}/profile/max-builds", user)
                .header("userId", user)
            )
            .andExpect(status().isOk())
            .andReturn();
        return objectMapper.readValue(result.getResponse().getContentAsString(), Integer.class);
    }
```
You can add these two utility methods, it will ease test readability

2024-08-30 08:51 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/UserProfileTest.java
> +            }
```suggestion
            assertEquals(
                Optional.ofNullable(maxAllowedCases).orElse(userAdminApplicationProps.getDefaultMaxAllowedCases()),
                profile1.get().getMaxAllowedCases()
            );
            assertEquals(
                Optional.ofNullable(maxAllowedBuilds).orElse(userAdminApplicationProps.getDefaultMaxAllowedBuilds()),
                profile1.get().getMaxAllowedBuilds()
            );
```
You can use optionals here :grin:

2024-08-30 08:51 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/UserProfileTest.java
You can add a test where you create a profile with the API with setting values and check that defualt values have been filled in the database

2024-08-30 11:39 UTC, achour94 commented on src/test/java/org/gridsuite/useradmin/server/UserProfileTest.java
it's already implemented :)

2024-08-30 12:46 UTC, TheMaskedTurtle approved these changes

2024-08-30 12:46 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/useradmin/server/NoQuotaTest.java
I love test files like that 😍

2024-08-30 13:04 UTC, achour94 commented on src/test/java/org/gridsuite/useradmin/server/NoQuotaTest.java
I love reviews like that :) Thank you for the comments

2024-08-30 13:05 UTC, merged