Display user information
gridsuite/user-admin-server pull request #43
Opened 2024-10-07 16:38 UTC by anistouri

2024-10-09 08:19 UTC, FranckLecuyer requested changes

2024-10-09 08:19 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/useradmin/server/service/UserInfosServiceTest.java
> +    private AdminRightService adminRightServiceMock;
Not used

2024-10-09 08:19 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/useradmin/server/service/UserInfosServiceTest.java
> +    private UserAdminApplicationProps applicationPropsMock;
Not used

2024-10-09 08:19 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/useradmin/server/service/UserInfosServiceTest.java
> +public class UserInfosServiceTest {
Remove public

2024-10-09 08:19 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/useradmin/server/service/UserInfosService.java
> +        Integer casesUsed = directoryService.getCasesCount(userInfosEntity.getSub());
Here, the rest call to directoryService is inside a transaction ....
I think you should separate this call from the following code (only the following code should be in a transaction)

2024-10-09 08:19 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/useradmin/server/entity/UserInfosEntity.java
> +    public static UserInfos toDto(@Nullable final UserInfosEntity userInfosEntity, Predicate<String> isAdminFn, Integer maxAllowedCases, Integer numberCasesUsed, Integer maxAllowedBuilds) {
Maybe rename into : toDtoWithDetail .... to avoid confusion with the other toDto method ?

2024-10-10 09:35 UTC, anistouri commented on src/test/java/org/gridsuite/useradmin/server/controller/UserInfosController.java
> +        assertEquals(false, userInfos.isAdmin());
Done

2024-10-10 09:35 UTC, anistouri commented on src/test/java/org/gridsuite/useradmin/server/service/UserInfosServiceTest.java
> +    private UserProfileRepository userProfileRepositoryMock;
They are used in the UserInfosService constructor

2024-10-10 09:35 UTC, anistouri commented on src/test/java/org/gridsuite/useradmin/server/service/UserInfosServiceTest.java
> +    private AdminRightService adminRightServiceMock;
Same remark above

2024-10-10 09:35 UTC, anistouri commented on src/test/java/org/gridsuite/useradmin/server/service/UserInfosServiceTest.java
> +    private UserAdminApplicationProps applicationPropsMock;
Same remark above

2024-10-10 09:35 UTC, anistouri commented on src/test/java/org/gridsuite/useradmin/server/service/UserInfosServiceTest.java
> +public class UserInfosServiceTest {
Done

2024-10-10 09:35 UTC, anistouri commented on src/main/java/org/gridsuite/useradmin/server/service/UserInfosService.java
> +        Integer casesUsed = directoryService.getCasesCount(userInfosEntity.getSub());
Done

2024-10-10 09:35 UTC, anistouri commented on src/main/java/org/gridsuite/useradmin/server/entity/UserInfosEntity.java
> +    public static UserInfos toDto(@Nullable final UserInfosEntity userInfosEntity, Predicate<String> isAdminFn, Integer maxAllowedCases, Integer numberCasesUsed, Integer maxAllowedBuilds) {
Done

2024-10-10 12:52 UTC, FranckLecuyer approved these changes

2024-10-11 10:03 UTC, achour94 approved these changes

2024-10-11 10:05 UTC, merged